version: "3.5"

services:
  postgres:
    image: postgres:13.5
    hostname: postgres
    ports:
      - "11111:5432"
    # volumes:
    #   - postgres_data_message_db2:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: message_store
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret

  message_db:
    build: ./
    depends_on:
      - postgres
    environment:
      CREATE_DATABASE: "off"
      DATABASE_NAME: message_store
      PGHOST: postgres
      PGUSER: admin
      PGPORT: 5432
      PGPASSWORD: secret
  
  postgrest:
    image: postgrest/postgrest
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://admin:secret@postgres:5432/message_store
      PGRST_DB_SCHEMA: message_store
      PGRST_DB_ANON_ROLE: admin #In production this role should not be the same as the one used for the connection
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000

  swagger:
    image: swaggerapi/swagger-ui
    depends_on:
      - postgrest
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      API_URL: http://localhost:3000/

# volumes:
#   postgres_data_message_db2: